"""add rate limit index

Revision ID: 0e605b57d5f3
Revises: ddc17a4d140f
Create Date: 2026-09-01 22:10:35.998189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e605b57d5f3'
down_revision: Union[str, Sequence[str], None] = 'ddc17a4d140f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_jobs_recipient_rate_limit', 'jobs', ['recipient', 'status', 'sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_recipient_rate_limit', table_name='jobs')
    # ### end Alembic commands ###
