"""add claimed_by claimed_at and claimable index

Revision ID: ddc17a4d140f
Revises: 56fc5e2c1f41
Create Date: 2026-09-01 20:34:52.717753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc17a4d140f'
down_revision: Union[str, Sequence[str], None] = '56fc5e2c1f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('claimed_by', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_jobs_claimable', 'jobs', ['status', 'priority', 'scheduled_for'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_claimable', table_name='jobs')
    op.drop_column('jobs', 'claimed_at')
    op.drop_column('jobs', 'claimed_by')
    # ### end Alembic commands ###
